######################################################################
# Automatically generated by qmake (2.01a) mar. déc. 6 12:01:41 2016
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += test.cc Interface.cc
