######################################################################
# Automatically generated by qmake (2.01a) mar. déc. 6 12:15:34 2016
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += test.cc
