######################################################################
# Automatically generated by qmake (2.01a) mar. déc. 6 11:11:47 2016
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += test.cc
